typedef struct no *Lista;
Lista criaLista();
int listaVazia(Lista li);
int insereElem(Lista *li, int element);
int removeElem(Lista *li, int element);
int tamanho(Lista li);
int esvaziar(Lista *li);
int removeMaior(Lista *li);
Lista inverter(Lista lst);
Lista multiplos3(Lista lst);
int removeTodos(Lista *lst, int elem);
Lista primos(Lista lst);
int obtem_valor(Lista lst, int Pos);
