

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author daniel
 */
public class VisualizarConta extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarConta
     */
    MenuPrincipal mp;
    String[] listaCPFs;

    
    public VisualizarConta(MenuPrincipal mp) {
        initComponents();
        this.mp = mp;
        
        NomeLabel.setVisible(false);
        NascimentoLabel.setVisible(false);
        SexoLabel.setVisible(false);
        NumContaLabel.setVisible(false);
        SenhaLabel.setVisible(false);
        EmailLabel.setVisible(false);
        NoticiasCheckBox.setVisible(false);
        
        
        if(this.mp != null)
        {
            setCPFBox();
        }
    }
    
    private void setCPFBox()
    {
        listaCPFs = mp.listaCPFs();
        if(listaCPFs != null)
        {
            for(String cpf : this.mp.listaCPFs())
            {
             CPFBox.addItem(cpf);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        EmailLabel = new javax.swing.JLabel();
        Fechar = new javax.swing.JButton();
        NoticiasCheckBox = new javax.swing.JCheckBox();
        NomeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NascimentoLabel = new javax.swing.JLabel();
        SexoLabel = new javax.swing.JLabel();
        NumContaLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        CPFBox = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar Conta");

        EmailLabel.setText("Email:");

        Fechar.setText("Fechar");
        Fechar.setToolTipText("");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });

        NoticiasCheckBox.setText("Desejo receber notícias");
        NoticiasCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoticiasCheckBoxActionPerformed(evt);
            }
        });

        NomeLabel.setText("Nome:");

        jLabel2.setText("CPF: ");

        NascimentoLabel.setText("Data de Nascimento:");

        SexoLabel.setText("Sexo: ");

        NumContaLabel.setText("Número da Conta:");

        SenhaLabel.setText("Senha: ");

        CPFBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NoticiasCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CPFBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NascimentoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(SexoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumContaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SenhaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(Fechar)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(NomeLabel)
                .addGap(18, 18, 18)
                .addComponent(NascimentoLabel)
                .addGap(12, 12, 12)
                .addComponent(SexoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NumContaLabel)
                .addGap(12, 12, 12)
                .addComponent(SenhaLabel)
                .addGap(12, 12, 12)
                .addComponent(EmailLabel)
                .addGap(12, 12, 12)
                .addComponent(NoticiasCheckBox)
                .addGap(31, 31, 31)
                .addComponent(Fechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharActionPerformed

    private void NoticiasCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoticiasCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoticiasCheckBoxActionPerformed

    private void CPFBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFBoxActionPerformed
        String CPF = (String) CPFBox.getSelectedItem();
        Conta c = mp.getConta(CPF);
        
        NomeLabel.setVisible(true);
        NascimentoLabel.setVisible(true);
        SexoLabel.setVisible(true);
        NumContaLabel.setVisible(true);
        SenhaLabel.setVisible(true);
        EmailLabel.setVisible(true);
        NoticiasCheckBox.setVisible(true);
        
        reiniciarText();
        
        NomeLabel.setText(NomeLabel.getText() + c.getNome());
        NascimentoLabel.setText(NascimentoLabel.getText() + c.getNascimento());
        SexoLabel.setText(SexoLabel.getText() + c.getSexo());
        NumContaLabel.setText(NumContaLabel.getText() + c.getNumeroConta());
        SenhaLabel.setText(SenhaLabel.getText() + c.getSenha());
        EmailLabel.setText(EmailLabel.getText() + c.getEmail());
        NoticiasCheckBox.setSelected(c.isNoticias());
    }//GEN-LAST:event_CPFBoxActionPerformed

    private void reiniciarText()
    {
        NomeLabel.setText("Nome: ");
        NascimentoLabel.setText("Data de Nascimento: ");
        SexoLabel.setText("Sexo: ");
        NumContaLabel.setText("Número da Conta: ");
        SenhaLabel.setText("Senha: ");
        EmailLabel.setText("Email: ");
        NoticiasCheckBox.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarConta(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CPFBox;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton Fechar;
    private javax.swing.JLabel NascimentoLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JCheckBox NoticiasCheckBox;
    private javax.swing.JLabel NumContaLabel;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JLabel SexoLabel;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables


}
