/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class pagamento extends javax.swing.JFrame {

    /**
     * Creates new form pagamento
     */
    
    sistema s;
    usuario u;
    
    public pagamento(sistema s) {
        initComponents();
        setLocationRelativeTo(null);
        SubPainel.setVisible(false);
        
        this.s = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CPFLabel = new javax.swing.JLabel();
        InserirCPFField = new javax.swing.JTextField();
        ProcurarButton = new javax.swing.JButton();
        AvisoLabel = new javax.swing.JLabel();
        SubPainel = new javax.swing.JPanel();
        NomeLabel = new javax.swing.JLabel();
        CarroLabel = new javax.swing.JLabel();
        VagaLabel = new javax.swing.JLabel();
        PagarLiberarButton = new javax.swing.JButton();
        TempoLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamento de estacionamento");
        setPreferredSize(new java.awt.Dimension(414, 346));

        CPFLabel.setText("CPF do usuário: ");

        InserirCPFField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirCPFFieldActionPerformed(evt);
            }
        });

        ProcurarButton.setText("Procurar");
        ProcurarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarButtonActionPerformed(evt);
            }
        });

        AvisoLabel.setForeground(new java.awt.Color(201, 9, 0));

        SubPainel.setBackground(new java.awt.Color(254, 254, 254));

        NomeLabel.setForeground(new java.awt.Color(1, 1, 1));
        NomeLabel.setText("Nome: ");

        CarroLabel.setForeground(new java.awt.Color(1, 1, 1));
        CarroLabel.setText("Carro Estacionado:");

        VagaLabel.setForeground(new java.awt.Color(1, 1, 1));
        VagaLabel.setText("Informações da vaga: ");

        PagarLiberarButton.setText("Pagar e Liberar");
        PagarLiberarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarLiberarButtonActionPerformed(evt);
            }
        });

        TempoLabel.setForeground(new java.awt.Color(1, 1, 1));
        TempoLabel.setText("Tempo: ");

        TotalLabel.setForeground(new java.awt.Color(1, 1, 1));
        TotalLabel.setText("Total:");

        javax.swing.GroupLayout SubPainelLayout = new javax.swing.GroupLayout(SubPainel);
        SubPainel.setLayout(SubPainelLayout);
        SubPainelLayout.setHorizontalGroup(
            SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CarroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VagaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TempoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPainelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PagarLiberarButton)
                .addGap(135, 135, 135))
        );
        SubPainelLayout.setVerticalGroup(
            SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VagaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TempoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalLabel)
                .addGap(18, 18, 18)
                .addComponent(PagarLiberarButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(SubPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(CPFLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InserirCPFField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ProcurarButton)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AvisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFLabel)
                    .addComponent(InserirCPFField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AvisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProcurarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirCPFFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirCPFFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirCPFFieldActionPerformed

    private void ProcurarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarButtonActionPerformed
        String cpf = InserirCPFField.getText();

        if(s.isUsuarioRegistrado(cpf))
        {
            u = s.getUsuario(cpf);
            if(u.getIndiceVagaOcupada() == -1)// nenhum carro estacionado
            {
                AvisoLabel.setText("Usuário não possui carro estacionado.");
                SubPainel.setVisible(false);
            }
            else
            {                
                int index =  u.getIndiceVagaOcupada();
                vaga v = s.getVaga(index);
                data d = v.getData();
                double total;
                
                
                NomeLabel.setText("Nome: " + u.getNome());
                CarroLabel.setText("Carro estacionado: " + u.getCarroEstacionado());
                VagaLabel.setText("Vaga " + v.getVisualizacao());
                if(v.getTipo().equals("Diaria"))
                {
                    TempoLabel.setText("Tempo: " + d.calculaIntervaloEmDias() + " dias");
                    total = d.calculaIntervaloEmDias() * v.getValor();
                }
                else
                {
                    TempoLabel.setText("Tempo: " + d.calculaIntervaloEmHoras() + " horas");
                    total = d.calculaIntervaloEmHoras() * v.getValor();
                }
                
                
                TotalLabel.setText("Valor a ser pago: R$" + total);
                                
                SubPainel.setVisible(true);                
            }
        }
        else
        {
            AvisoLabel.setText("Usuário não registrado.");
            SubPainel.setVisible(false);
        }
    }//GEN-LAST:event_ProcurarButtonActionPerformed

    private void PagarLiberarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarLiberarButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Vaga Paga", "Vaga Paga e Liberada.", JOptionPane.OK_OPTION);
        
        int index =  u.getIndiceVagaOcupada();
        
        s.desocuparVaga(index);
        u.setCarroEstacionado("");
        u.setIndiceVagaOcupada(-1);
        
        this.dispose();
    }//GEN-LAST:event_PagarLiberarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagamento(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvisoLabel;
    private javax.swing.JLabel CPFLabel;
    private javax.swing.JLabel CarroLabel;
    private javax.swing.JTextField InserirCPFField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JButton PagarLiberarButton;
    private javax.swing.JButton ProcurarButton;
    private javax.swing.JPanel SubPainel;
    private javax.swing.JLabel TempoLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel VagaLabel;
    // End of variables declaration//GEN-END:variables
}
