/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema;

import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    
    sistema s;
    usuario u;
    
    public registro(sistema s) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.s = s;
        SubPainel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel3 = new javax.swing.JLabel();
        InserirCPFField = new javax.swing.JTextField();
        ProcurarButton = new javax.swing.JButton();
        AvisoLabel = new javax.swing.JLabel();
        SubPainel = new javax.swing.JPanel();
        NomeUsuarioLabel = new javax.swing.JLabel();
        ConsultarButton = new javax.swing.JButton();
        CarroLabel = new javax.swing.JLabel();
        PeriodoInicialLabel = new javax.swing.JLabel();
        ComboBoxCarros = new javax.swing.JComboBox<>();
        PeriodoFinalLabel = new javax.swing.JLabel();
        DiaHoraMinutoLabel = new javax.swing.JLabel();
        ComboBoxDiaInicial = new javax.swing.JComboBox<>();
        ComboBoxDiaFinal = new javax.swing.JComboBox<>();
        ComboBoxHoraInicial = new javax.swing.JComboBox<>();
        ComboBoxHoraFinal = new javax.swing.JComboBox<>();
        ComboBoxMinutoInicial = new javax.swing.JComboBox<>();
        ComboBoxMinutoFinal = new javax.swing.JComboBox<>();
        AvisoLabel2 = new javax.swing.JLabel();
        FecharButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro e Consulta de vagas");

        jLabel3.setText("CPF do usuário: ");

        InserirCPFField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirCPFFieldActionPerformed(evt);
            }
        });

        ProcurarButton.setText("Procurar");
        ProcurarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarButtonActionPerformed(evt);
            }
        });

        AvisoLabel.setForeground(new java.awt.Color(201, 9, 0));

        SubPainel.setBackground(new java.awt.Color(254, 254, 254));

        NomeUsuarioLabel.setForeground(new java.awt.Color(1, 1, 1));
        NomeUsuarioLabel.setToolTipText("");

        ConsultarButton.setText("Consultar");
        ConsultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarButtonActionPerformed(evt);
            }
        });

        CarroLabel.setForeground(new java.awt.Color(1, 1, 1));
        CarroLabel.setText("Carro: ");

        PeriodoInicialLabel.setForeground(new java.awt.Color(1, 1, 1));
        PeriodoInicialLabel.setText("Período inicial: ");

        PeriodoFinalLabel.setForeground(new java.awt.Color(1, 1, 1));
        PeriodoFinalLabel.setText("Período final: ");

        DiaHoraMinutoLabel.setForeground(new java.awt.Color(1, 1, 1));
        DiaHoraMinutoLabel.setText("         Dia                 Hora                 Min");

        ComboBoxDiaInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        ComboBoxDiaInicial.setSelectedIndex(-1);

        ComboBoxDiaFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        ComboBoxDiaFinal.setSelectedIndex(-1);

        ComboBoxHoraInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        ComboBoxHoraInicial.setSelectedIndex(-1);

        ComboBoxHoraFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        ComboBoxHoraFinal.setSelectedIndex(-1);

        ComboBoxMinutoInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        ComboBoxMinutoInicial.setSelectedIndex(-1);

        ComboBoxMinutoFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        ComboBoxMinutoFinal.setSelectedIndex(-1);

        AvisoLabel2.setForeground(new java.awt.Color(201, 9, 0));

        FecharButton.setText("Fechar");
        FecharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubPainelLayout = new javax.swing.GroupLayout(SubPainel);
        SubPainel.setLayout(SubPainelLayout);
        SubPainelLayout.setHorizontalGroup(
            SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPainelLayout.createSequentialGroup()
                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubPainelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SubPainelLayout.createSequentialGroup()
                                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(SubPainelLayout.createSequentialGroup()
                                        .addComponent(PeriodoInicialLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxDiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(ComboBoxHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SubPainelLayout.createSequentialGroup()
                                        .addComponent(PeriodoFinalLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBoxDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ComboBoxHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxMinutoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxMinutoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SubPainelLayout.createSequentialGroup()
                                .addComponent(CarroLabel)
                                .addGap(18, 18, 18)
                                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiaHoraMinutoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(SubPainelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AvisoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SubPainelLayout.createSequentialGroup()
                                .addComponent(ConsultarButton)
                                .addGap(63, 63, 63)
                                .addComponent(FecharButton)))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubPainelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(NomeUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        SubPainelLayout.setVerticalGroup(
            SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeUsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarroLabel))
                .addGap(8, 8, 8)
                .addComponent(DiaHoraMinutoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboBoxDiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(ComboBoxHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(ComboBoxMinutoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(PeriodoInicialLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PeriodoFinalLabel)
                    .addComponent(ComboBoxDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMinutoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AvisoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(SubPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultarButton)
                    .addComponent(FecharButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(ProcurarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AvisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InserirCPFField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SubPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InserirCPFField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AvisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProcurarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserirCPFFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirCPFFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirCPFFieldActionPerformed

    private void ProcurarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarButtonActionPerformed
        String cpf = InserirCPFField.getText();
        
        if(s.isUsuarioRegistrado(cpf))
        {
            u = s.getUsuario(cpf);
            if(u.getIndiceVagaOcupada() != -1)// carro estacionado
            {
                AvisoLabel.setText("Usuário já possui um carro estacionado.");
                SubPainel.setVisible(false);    
            }
            else
            {
                ComboBoxCarros.removeAllItems();
                
                AvisoLabel.setText("");
                for(String car : u.getCarros())
                    ComboBoxCarros.addItem(car);
                NomeUsuarioLabel.setText(u.getNome());
                SubPainel.setVisible(true);    
            }
        }
        else
        {
            AvisoLabel.setText("Usuário não registrado.");
            SubPainel.setVisible(false);    
        }
    }//GEN-LAST:event_ProcurarButtonActionPerformed

    private void ConsultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarButtonActionPerformed
        int selecionado = ComboBoxCarros.getSelectedIndex();
        
        if(selecionado == 0)
        {
            AvisoLabel2.setText("Nenhum carro foi selecionado.");
        }
        else
        {
            if(ComboBoxDiaFinal.getSelectedIndex() == -1 || ComboBoxDiaInicial.getSelectedIndex() == -1 || 
               ComboBoxHoraFinal.getSelectedIndex() == -1 || ComboBoxHoraInicial.getSelectedIndex() == -1 || 
               ComboBoxMinutoFinal.getSelectedIndex() == -1 || ComboBoxMinutoInicial.getSelectedIndex() == -1)
            {
               AvisoLabel2.setText("A data não foi preenchida corretamente.");     
            }
            else
            {
                // caso que realiza a consulta das vagas
                String[] vagas = s.getVagasDisponives(s.getCategoriaCarro(ComboBoxCarros.getItemAt(selecionado)), u.isVIP());
                if(vagas.length != 0)
                {
                    String escolha = (String) JOptionPane.showInputDialog(null,"Escolha a vaga para estacionar: ", "Vagas", 
                            JOptionPane.QUESTION_MESSAGE, null,vagas,vagas[0]);
                   
                    String vetor[] = escolha.split(" ");
                    int index = Integer.valueOf(vetor[0]);

                    u.setIndiceVagaOcupada(index);
                    u.setCarroEstacionado((String) ComboBoxCarros.getSelectedItem());

                    data d = new data(Integer.valueOf(ComboBoxHoraInicial.getSelectedItem().toString()), Integer.valueOf(ComboBoxMinutoInicial.getSelectedItem().toString()), 
                            Integer.valueOf(ComboBoxDiaInicial.getSelectedItem().toString()), Integer.valueOf(ComboBoxHoraFinal.getSelectedItem().toString()), 
                            Integer.valueOf(ComboBoxMinutoFinal.getSelectedItem().toString()), Integer.valueOf(ComboBoxDiaFinal.getSelectedItem().toString()));

                    s.ocuparVaga(index,d);  

                    AvisoLabel2.setText("Operação bem sucedida!");
                    SubPainel.setVisible(false);
                }
                else
                {
                    AvisoLabel2.setText("Nenhuma vaga disponível para o carro selecionado.");
                }
            }
        }
      
    }//GEN-LAST:event_ConsultarButtonActionPerformed

    private void FecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvisoLabel;
    private javax.swing.JLabel AvisoLabel2;
    private javax.swing.JLabel CarroLabel;
    private javax.swing.JComboBox<String> ComboBoxCarros;
    private javax.swing.JComboBox<String> ComboBoxDiaFinal;
    private javax.swing.JComboBox<String> ComboBoxDiaInicial;
    private javax.swing.JComboBox<String> ComboBoxHoraFinal;
    private javax.swing.JComboBox<String> ComboBoxHoraInicial;
    private javax.swing.JComboBox<String> ComboBoxMinutoFinal;
    private javax.swing.JComboBox<String> ComboBoxMinutoInicial;
    private javax.swing.JButton ConsultarButton;
    private javax.swing.JLabel DiaHoraMinutoLabel;
    private javax.swing.JButton FecharButton;
    private javax.swing.JTextField InserirCPFField;
    private javax.swing.JLabel NomeUsuarioLabel;
    private javax.swing.JLabel PeriodoFinalLabel;
    private javax.swing.JLabel PeriodoInicialLabel;
    private javax.swing.JButton ProcurarButton;
    private javax.swing.JPanel SubPainel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
